title: Leandro Stival | AI Researcher
author: Leandro Stival
email: leandro.stival@wur.nl
description: Leandro Stival is a researcher in Artificial Intelligence specializing in Self-Supervised Learning, Multimodal Data, and Remote Sensing.
keywords: Artificial Intelligence Researcher, Self-Supervised Learning, Multimodal Learning, Spatio-Temporal Data, Remote Sensing, Time Series Analysis, Representation Learning, Foundation Models, Computer Vision, Machine Learning Research
url: "https://lstival.github.io"
baseurl: ""
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Research
    url: /research-areas/
  - title: Publications
    url: /publications/
  - title: Projects
    url: /projects/
  - title: Teaching
    url: /teaching/
  - title: CV
    url: /cv/

social_links:
  - label: Email
    title: Email
    url: "mailto:leandro.stival@wur.nl"
  - label: GitHub
    title: GitHub
    url: "https://github.com/lstival"
  - label: Google Scholar
    title: Google Scholar
    url: "https://scholar.google.com/citations?user=Bw3dn34AAAAJ&hl=en"
  - label: LinkedIn
    title: LinkedIn
    url: "https://www.linkedin.com/in/leandro-stival-63651ba0"
  - label: ORCID
    title: ORCID
    url: "https://orcid.org/0000-0002-3379-6813"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - .github
  - .git
  - .gitignore
  - .vscode
